export * from "./Welcome";
export * from "./DefaultContent";
export * from "./RequestLoan";
export * from "./FillLoan";
export * from "./Dashboard";
export * from "./TestForm";
export * from "./Terms";
export * from "./Privacy";
export * from "./EnsureAgreedToTerms";
