import { LoanEntity } from '../../models';

export const loans: LoanEntity[] =
[
	{
		id: 'asdfGH',
		amount: 10,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'SNT',
		collateralAmount: 15,
		collateralCurrency: 'SNT',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 6,
		terms: 'simple',
		installments: true,
		amountPaid: 4,
		active: true,
		paid: false,
		createdOnTimestamp: 1514764800,
		paidOnTimestamp: 0
	},
	{
		id: 'Iihwdko',
		amount: 3,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'MKR',
		collateralAmount: 20,
		collateralCurrency: 'MKR',
		collateralLockupPeriod: '1week',
		collateralCustomLockupPeriod: 0,
		terms: 'compound',
		installments: false,
		amountPaid: 0,
		active: true,
		paid: false,
		createdOnTimestamp: 1517961600,
		paidOnTimestamp: 0
	},
	{
		id: 'OWJceb',
		amount: 5,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'REP',
		collateralAmount: 6,
		collateralCurrency: 'REP',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 10,
		terms: 'simple',
		installments: true,
		amountPaid: 1,
		active: true,
		paid: false,
		createdOnTimestamp: 1515974400,
		paidOnTimestamp: 0
	},
	{
		id: 'owek9n',
		amount: 10,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'SNT',
		collateralAmount: 15,
		collateralCurrency: 'SNT',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 6,
		terms: 'simple',
		installments: true,
		amountPaid: 10,
		active: false,
		paid: true,
		createdOnTimestamp: 1511827200,
		paidOnTimestamp: 1517097600
	},
	{
		id: 'kqjYlk',
		amount: 3,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'OMG',
		collateralAmount: 10,
		collateralCurrency: 'OMG',
		collateralLockupPeriod: '1week',
		collateralCustomLockupPeriod: 0,
		terms: 'compound',
		installments: false,
		amountPaid: 3,
		active: false,
		paid: true,
		createdOnTimestamp: 1515628800,
		paidOnTimestamp: 1516320000
	}
];
