import { InvestmentEntity } from '../../models';

export const investments: InvestmentEntity[] =
[
	{
		id: '0xBEjTPZdrWjn6ocmcUWBX',
		loanId: 'asdfGH',
		amountLended: 10,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'SNT',
		collateralAmount: 15,
		collateralCurrency: 'SNT',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 6,
		terms: 'simple',
		installments: true,
		amountPaid: 4,
		active: true,
		defaulted: false,
		collected: false,
		paid: false,
		createdOnTimestamp: 1514764800,
		paidOnTimestamp: 0,
		defaultedOnTimestamp: 0,
		collectedOnTimestamp: 0
	},
	{
		id: '0xWYX495SIfi3QRb7KKkJA',
		loanId: 'Iihwdko',
		amountLended: 3,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'MKR',
		collateralAmount: 20,
		collateralCurrency: 'MKR',
		collateralLockupPeriod: '1week',
		collateralCustomLockupPeriod: 0,
		terms: 'compound',
		installments: false,
		amountPaid: 0,
		active: true,
		defaulted: false,
		collected: false,
		paid: false,
		createdOnTimestamp: 1517961600,
		paidOnTimestamp: 0,
		defaultedOnTimestamp: 0,
		collectedOnTimestamp: 0
	},
	{
		id: '0xCrlkdyeSFVZwry8EjUE3',
		loanId: 'OWJceb',
		amountLended: 5,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'REP',
		collateralAmount: 6,
		collateralCurrency: 'REP',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 10,
		terms: 'simple',
		installments: true,
		amountPaid: 1,
		active: true,
		defaulted: true,
		collected: false,
		paid: false,
		createdOnTimestamp: 1515974400,
		paidOnTimestamp: 0,
		defaultedOnTimestamp: 1518652800,
		collectedOnTimestamp: 0
	},
	{
		id: '0xZSRf9O0VLnYOoRCYVMDd',
		loanId: 'owek9n',
		amountLended: 10,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'SNT',
		collateralAmount: 15,
		collateralCurrency: 'SNT',
		collateralLockupPeriod: 'custom',
		collateralCustomLockupPeriod: 6,
		terms: 'simple',
		installments: true,
		amountPaid: 8,
		active: false,
		defaulted: true,
		collected: true,
		paid: false,
		createdOnTimestamp: 1511827200,
		paidOnTimestamp: 0,
		defaultedOnTimestamp: 1514592000,
		collectedOnTimestamp: 1514851200
	},
	{
		id: '0xK6QHU6BRgzVbiu9OAehD',
		loanId: 'kqjYlk',
		amountLended: 3,
		currency: 'ETH',
		collateralized: true,
		collateralSource: 'OMG',
		collateralAmount: 10,
		collateralCurrency: 'OMG',
		collateralLockupPeriod: '1week',
		collateralCustomLockupPeriod: 0,
		terms: 'compound',
		installments: false,
		amountPaid: 3,
		active: false,
		defaulted: false,
		collected: false,
		paid: true,
		createdOnTimestamp: 1515628800,
		paidOnTimestamp: 1516320000,
		defaultedOnTimestamp: 0,
		collectedOnTimestamp: 0
	}
];
