export const actionsEnums = {
	WEB3_CONNECTED: 'WEB3_CONNECTED',
	DHARMA_INSTANTIATED: 'DHARMA_INSTANTIATED',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	REQUEST_DEBT_ORDER: 'REQUEST_DEBT_ORDER',
	GET_DEBT_ORDER: 'GET_DEBT_ORDER',
};
