export const actionsEnums = {
	WEB3_CONNECTED: 'WEB3_CONNECTED',
	DHARMA_INSTANTIATED: 'DHARMA_INSTANTIATED',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_GLOBAL_ERROR: 'SET_GLOBAL_ERROR',
	REQUEST_DEBT_ORDER: 'REQUEST_DEBT_ORDER',
	GET_DEBT_ORDER: 'GET_DEBT_ORDER',
	SET_ALL_TOKENS_TRADING_PERMISSION: 'SET_ALL_TOKENS_TRADING_PERMISSION',
	TOGGLE_TOKEN_TRADING_PERMISSION: 'TOGGLE_TOKEN_TRADING_PERMISSION'
};
