export const actionsEnums = {
	WEB3_CONNECTED: 'WEB3_CONNECTED',
	DHARMA_INSTANTIATED: 'DHARMA_INSTANTIATED',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_ERROR: 'SET_ERROR',
	REQUEST_DEBT_ORDER: 'REQUEST_DEBT_ORDER',
	GET_PENDING_DEBT_ORDER: 'GET_PENDING_DEBT_ORDER',
	FILL_DEBT_ORDER: 'FILL_DEBT_ORDER',
	SET_ALL_TOKENS_TRADING_PERMISSION: 'SET_ALL_TOKENS_TRADING_PERMISSION',
	TOGGLE_TOKEN_LOADING_SPINNER: 'TOGGLE_TOKEN_LOADING_SPINNER',
	TOGGLE_TOKEN_TRADING_PERMISSION: 'TOGGLE_TOKEN_TRADING_PERMISSION',
	SET_TOKEN_BALANCE: 'SET_TOKEN_BALANCE',
	SET_DEBT_ORDERS: 'SET_DEBT_ORDERS',
	SET_INVESTMENTS: 'SET_INVESTMENTS',
	FILL_DEBT_ORDER: 'FILL_DEBT_ORDER',
    FAUCET_TOKEN_REQUEST: 'FAUCET_TOKEN_REQUEST'
};
