export const KOVAN_NETWORK_ID = 42;
export const LOCAL_NETWORK_ID = 1457;

export const SUPPORTED_NETWORK_IDS = new Array(KOVAN_NETWORK_ID, LOCAL_NETWORK_ID);

export const BLOCKCHAIN_API = {
    POLLING_INTERVAL: 1000,
    TIMEOUT: 60000,
};
